version: "3.8"
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    container_name: angular_app
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:
        - PORT = ${PORT}
    volumes:
      - ./frontend:/app
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    command: npm start
volumes:
  postgres:
    driver: local
